# Generated by Django 5.2.7 on 2025-10-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getaway', '0003_tripimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='places',
            new_name='num_people',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='event',
            new_name='trip',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Guest', max_length=100),
            preserve_default=False,
        ),
    ]
