# Generated by Django 5.2.7 on 2025-11-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getaway', '0004_rename_booked_at_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
