# Generated by Django 5.2.7 on 2025-11-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getaway', '0006_booking_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_images/'),
        ),
    ]
