# Generated by Django 5.2.7 on 2025-12-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getaway', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='sustainability_score',
            field=models.IntegerField(default=5, help_text='Overall sustainability rating: 1 (low) to 5 (high)'),
        ),
    ]
